# @format
---
- name: Fix Docker Sources Conflicts
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - ../common/vars/server_vars.yml

  tasks:
    - name: Create backup of current sources.list
      copy:
        src: /etc/apt/sources.list
        dest: "/etc/apt/sources.list.backup.{{ ansible_date_time.epoch }}"
        remote_src: yes
        backup: yes
      ignore_errors: yes

    - name: Remove Docker entries from main sources.list
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '.*docker\.com.*'
        state: absent
      ignore_errors: yes

    - name: Remove Docker entries from main sources.list (case sensitive)
      lineinfile:
        path: /etc/apt/sources.list
        regexp: ".*Docker.*"
        state: absent
      ignore_errors: yes

    - name: Find all docker-related files in sources.list.d
      find:
        paths: /etc/apt/sources.list.d
        patterns: "*docker*"
      register: docker_source_files

    - name: Remove docker-related source files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ docker_source_files.files }}"
      ignore_errors: yes

    - name: Remove specific docker source files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/sources.list.d/docker.list.save
        - /etc/apt/sources.list.d/docker-ce.list
      ignore_errors: yes

    - name: Remove Docker GPG keys
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/share/keyrings/docker-archive-keyring.gpg
        - /usr/share/keyrings/docker.gpg
        - /etc/apt/trusted.gpg.d/docker.gpg
      ignore_errors: yes

    - name: Clean apt cache
      shell: apt-get clean
      ignore_errors: yes

    - name: Remove apt lists
      shell: rm -rf /var/lib/apt/lists/*
      ignore_errors: yes

    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 0
      register: apt_update_result
      retries: 3
      delay: 5

    - name: Display cleanup results
      debug:
        msg: "Docker sources cleanup completed successfully on {{ inventory_hostname }}"

  handlers:
    - name: restart apt-daily services
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - apt-daily.service
        - apt-daily-upgrade.service
      ignore_errors: yes
