# @format
---
- name: Update Aztec to Latest Version
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - ../common/vars/server_vars.yml

  tasks:
    - name: Run aztec-up latest command
      shell: |
        echo "=== Starting Aztec Update Process ==="
        echo "Server: {{ inventory_hostname }}"
        echo "Date: $(date)"
        echo "Current user: $(whoami)"
        echo "Running aztec-up latest with retry..."

        # Retry mechanism for network issues
        for attempt in 1 2 3; do
          echo "Attempt $attempt of 3..."
          if bash -l -c "aztec-up latest" 2>&1; then
            echo "Update successful on attempt $attempt"
            break
          else
            exit_code=$?
            echo "Attempt $attempt failed with exit code: $exit_code"
            if [ $attempt -eq 3 ]; then
              echo "All attempts failed, giving up"
              exit $exit_code
            else
              echo "Waiting 10 seconds before retry..."
              sleep 10
            fi
          fi
        done

        echo "Restarting service..."
        systemctl restart aztec-node.service

        echo "Update process completed"
      args:
        executable: /bin/bash
      register: aztec_update_result
      async: 1800 # 30 minutes timeout (increased)
      poll: 15
      retries: 1
      delay: 30

    - name: Show aztec-up output
      debug:
        var: aztec_update_result.stdout_lines

    - name: Check service status after update
      shell: systemctl status aztec-node.service --no-pager -l
      register: service_status
      ignore_errors: yes

    - name: Display update results
      debug:
        msg: |
          Update completed on {{ inventory_hostname }}
          Service status: {{ service_status.stdout_lines[1] if service_status.stdout_lines|length > 1 else 'Unknown' }}

  handlers:
    - name: restart aztec service
      systemd:
        name: aztec-node.service
        state: restarted
        enabled: yes
