# @format
---
- name: Update Aztec to Latest Version
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - ../common/vars/server_vars.yml

  tasks:
    - name: Run aztec-up latest command
      shell: |
        echo "=== Starting Aztec Update Process ==="
        echo "Server: {{ inventory_hostname }}"
        echo "Date: $(date)"
        echo "Running aztec-up latest..."
        aztec-up latest
        echo "Update command completed with exit code: $?"
      args:
        executable: /bin/bash
      register: aztec_update_result
      async: 1200 # 20 minutes timeout
      poll: 10
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin:/root/.local/bin:{{ ansible_env.PATH }}"

    - name: Check service status after update
      shell: systemctl status aztec-node.service --no-pager -l
      register: service_status
      ignore_errors: yes

    - name: Display update results
      debug:
        msg: |
          Update completed on {{ inventory_hostname }}
          Service status: {{ service_status.stdout_lines[1] if service_status.stdout_lines|length > 1 else 'Unknown' }}

  handlers:
    - name: restart aztec service
      systemd:
        name: aztec-node.service
        state: restarted
        enabled: yes
