# @format
---
- name: Fix testnet parameter in start_aztec_node.sh
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update alpha-testnet to testnet in start_aztec_node.sh
      shell: |
        echo "=== Starting Testnet Parameter Fix ==="
        echo "Server: {{ inventory_hostname }}"
        echo "Date: $(date)"
        echo "Current user: $(whoami)"
        echo "Fixing testnet parameter in start_aztec_node.sh..."

        # Check if file exists
        if [ ! -f "$HOME/start_aztec_node.sh" ]; then
          echo "ERROR: File $HOME/start_aztec_node.sh not found!"
          exit 1
        fi

        # Show current content with testnet parameter
        echo "Current testnet parameter in file:"
        grep -n "alpha-testnet" "$HOME/start_aztec_node.sh" || echo "No alpha-testnet found in file"

        # Apply the fix
        sed -i 's/alpha-testnet/testnet/g' "$HOME/start_aztec_node.sh"

        echo "Fix applied successfully"
        echo "Updated testnet parameter in file:"
        grep -n "testnet" "$HOME/start_aztec_node.sh" || echo "No testnet found in file"
      args:
        executable: /bin/bash
      register: fix_result

    - name: Display fix result
      debug:
        var: fix_result.stdout_lines
