# @format
---
- name: Update validator private keys and restart Aztec node
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - ../common/vars/server_vars.yml

  tasks:
    - name: Upload update script to server
      template:
        src: templates/update_keys.sh.j2
        dest: /tmp/update_validator_keys.sh
        mode: "0755"

    - name: Execute update script
      command: /tmp/update_validator_keys.sh
      register: update_result

    - name: Remove temporary script
      file:
        path: /tmp/update_validator_keys.sh
        state: absent

    - name: Display update result
      debug:
        var: update_result.stdout_lines

    - name: Restart aztec-node service
      systemd:
        name: aztec-node.service
        state: restarted
        enabled: yes
      register: restart_result

    - name: Wait for service to start
      wait_for:
        timeout: 30
      delegate_to: localhost

    - name: Check service status after restart
      shell: systemctl status aztec-node.service --no-pager -l
      register: service_status
      ignore_errors: yes

    - name: Display restart results
      debug:
        msg: |
          Restart completed on {{ inventory_hostname }}
          Service status: {{ service_status.stdout_lines[2] if service_status.stdout_lines|length > 2 else 'Unknown' }}
          Active state: {{ 'Active' if 'active (running)' in service_status.stdout else 'Inactive/Failed' }}

    - name: Verify service is running
      shell: systemctl is-active aztec-node.service
      register: is_active
      failed_when: is_active.stdout != "active"

    - name: Final success message
      debug:
        msg: |
          ===========================================
          Validator keys updated successfully!
          Aztec node restarted and is running.
          Server: {{ inventory_hostname }}
          ===========================================
