# @format
---
- name: Add Aztec hosts to Zabbix monitoring
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    zabbix_server: "{{ lookup('env', 'ZABBIX_SERVER') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    zabbix_user: "{{ lookup('env', 'ZABBIX_USER') }}"
    zabbix_password: "{{ lookup('env', 'ZABBIX_PASSWORD') }}"
    inventory_file: "{{ inventory_file_path | default('../common/inventory/hosts') }}"
    script_path: "{{ script_file_path | default('./add_aztec_hosts_to_zabbix.sh') }}"

  pre_tasks:
    - name: Validate required environment variables
      fail:
        msg: "ZABBIX_SERVER environment variable is not set"
      when: zabbix_server == ""

    - name: Validate authentication method
      fail:
        msg: |
          No valid authentication method configured!
          Please set either:
          - ZABBIX_API_TOKEN (recommended)
          - ZABBIX_USER + ZABBIX_PASSWORD (legacy)
      when:
        - zabbix_api_token == ""
        - (zabbix_user == "" or zabbix_password == "")

    - name: Check if inventory file exists
      stat:
        path: "{{ inventory_file }}"
      register: inventory_check

    - name: Fail if inventory file does not exist
      fail:
        msg: "Inventory file {{ inventory_file }} does not exist"
      when: not inventory_check.stat.exists

    - name: Check if Zabbix script exists
      stat:
        path: "{{ script_path }}"
      register: script_check

    - name: Fail if Zabbix script does not exist
      fail:
        msg: "Zabbix script {{ script_path }} does not exist"
      when: not script_check.stat.exists

    - name: Make script executable
      file:
        path: "{{ script_path }}"
        mode: "0755"

  tasks:
    - name: Display configuration
      debug:
        msg: |
          Zabbix Server: {{ zabbix_server }}
          Authentication: {% if zabbix_api_token != "" %}API Token (***{{ zabbix_api_token[-4:] }}){% else %}Username/Password ({{ zabbix_user }}){% endif %}
          Inventory File: {{ inventory_file }}
          Script Path: {{ script_path }}

    - name: Run Zabbix host addition script
      shell: |
        export ZABBIX_SERVER="{{ zabbix_server }}"
        export ZABBIX_API_TOKEN="{{ zabbix_api_token }}"
        export ZABBIX_USER="{{ zabbix_user }}"
        export ZABBIX_PASSWORD="{{ zabbix_password }}"
        {{ script_path }} {{ inventory_file }}
      register: script_result
      changed_when: true

    - name: Display script output
      debug:
        var: script_result.stdout_lines

    - name: Display script errors if any
      debug:
        var: script_result.stderr_lines
      when: script_result.stderr_lines is defined and script_result.stderr_lines | length > 0

    - name: Check script exit code
      fail:
        msg: "Script failed with exit code {{ script_result.rc }}"
      when: script_result.rc != 0
